name: atlast
maria_params:
  scan_center: [291.156, -31.23]
  map_filename: "maps/big_cluster.fits"
  site: 'llano_de_chajnantor'
  # resolution: null
  resolution: 0.0009765625
  nu: 91.5e+9
  nu_width: 51.e+09
  NET_RJ: 266.e-06
  width: 1.
  scan_options:
    radius: 0.25
    speed: 0.5
  duration: 60
  sample_rate: 225
  field_of_view: 1.0
  beam_spacing: 2
  start_time: "2024-08-06T03:00:00"
  units: Jy/pixel
nifty_params:
  noiseval: 0.00028
  tod_offset : [5.0e-5, 1.0e-5]
  tod_fluct : [0.113, 0.003]
  tod_loglog : [-2.8, 0.2]
  map_offset : [5.3e-7, 1.0e-7]
  map_fluct : [6.1e-5, 1.0e-6]
  map_loglog : [-3.6, 0.1]
  downsampling_factor: 5