name: mustang
maria_params:
  scan_center: [144, 12]
  map_filename: "maps/small_cluster.h5"
  site: 'green_bank'
  resolution: 8.714e-05
  nu: 93.0e+9
  width: 0.08714
  scan_options:
    radius: 0.0333
    speed: 0.008333
  duration: 1800
  # duration: 600
  sample_rate: 50
  start_time: '2024-02-10T06:00:00.000'
  units: mJy/pixel
nifty_params:
  # noiseval: 2.5e-4
  noiseval: 1.6e-4
  tod_offset : [1.0e-5, 0.99e-5]
  tod_fluct : [0.0015, 0.0001]
  tod_loglog : [-2.45, 0.1]
  map_offset : [1.0e-8, 1.0e-7]
  map_fluct : [5.6e-5, 1.0e-6]
  map_loglog : [-2.5, 0.1]
  downsampling_factor: 1