name: mustang
maria_params:
  scan_center: [144, 12]
  map_filename: "maps/cluster.fits"
  site: 'green_bank'
  resolution: 8.714e-05
  nu: 930e9
  width: null
  scan_options:
    radius: 0.0333
    speed: 0.008333
  duration: 1200
  sample_rate: 50
  start_time: null
  units: Jy/pixel
nifty_params:
  noiseval: 2.5e-4
  tod_offset : [1.0e-5, 0.99e-5]
  tod_fluct : [0.0015, 0.0001]
  tod_loglog : [-2.45, 0.1]
  map_offset : [1.0e-8, 1.0e-7]
  map_fluct : [5.6e-5, 1.0e-6]
  map_loglog : [-2.5, 0.1]
  downsampling_factor: 1